[fr]
[[offers]]
title = "Serveur 1"
tint = "255, 99, 132"
cpu = "2x Xeon"
ram = "8 Go"
storage = "100 Go"
bandwidth = "1 Gbps"
price = "30€"

[en]
[[offers]]
title = "Server 1"
tint = "255, 99, 132"
cpu = "2x Xeon"
ram = "8 GB"
storage = "100 GB"
bandwidth = "1 Gbps"
price = "$35"
